### ISSUE TITLE
[macOS] CPU/Swap mem graph freely movable

### ISSUE THREAD

**Issue by dbxnr** [ajinkyakadam/monitorstats#1]
The graph can be moved around freely to display +/-100 on the axes. If you do move the graph, the lines themselves appear to creep along like a snake rather than staying within the bounds of the window.

![graphscreenshot](https://cloud.githubusercontent.com/assets/17500013/24061020/a79a50b8-0b4d-11e7-9182-a397a7a36d7d.png)

**Comment by ajinkyakadam** [comment]
Added limits to both axes so that the plot moves within constraint limits. Refer this commit https://github.com/ajinkyakadam/monitorstats/commit/2048fed6e9d2b6948dbf8f897235434ecba2d3a2
